# -*- coding: utf-8 -*-
"""algorithms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tS-IqNB4Sh02kxmIakOMVwxPkLuhgtHB
"""

"""
Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.
"""

def containsDuplicate(self, nums):
    hashset = {}
    for i in range(len(nums)):
        if nums[i] not in hashset:
            hashset[nums[i]] = True
        else:
            return True
    return False