# -*- coding: utf-8 -*-
"""algorithms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tS-IqNB4Sh02kxmIakOMVwxPkLuhgtHB
"""

"""
Given an integer x, return true if x is a 
palindrome, and false otherwise 
"""

def isPalindrome(self, x):
   return (str(x) == str(x)[::-1])