# -*- coding: utf-8 -*-
"""algorithms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tS-IqNB4Sh02kxmIakOMVwxPkLuhgtHB
"""

"""
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

"""

def twoSum(self, nums, target):
    hashset = {}
    for idx, val in enumerate(nums):
        if target - val not in hashset:
            hashset[val] = idx
        else:
            return [idx, hashset[target-val]]